In [1]:
import pandas as pd

In [2]:
_91_data=pd.read_csv("NYCHVS 1991 Occupied File for ASA Challenge_CSV.csv")
_93_data=pd.read_csv("NYCHVS 1993 Occupied File for ASA Challenge_CSV.csv")
_96_data=pd.read_csv("NYCHVS 1996 Occupied File for ASA Challenge_CSV.csv")
_99_data=pd.read_csv("NYCHVS 1999 Occupied File for ASA Challenge_CSV.csv")
_02_data=pd.read_csv("NYCHVS 2002 Occupied File for ASA Challenge_CSV.csv")
_05_data=pd.read_csv("NYCHVS 2005 Occupied File for ASA Challenge_CSV.csv")
_08_data=pd.read_csv("NYCHVS 2008 Occupied File for ASA Challenge_CSV.csv")
_11_data=pd.read_csv("NYCHVS 2011 Occupied File for ASA Challenge_CSV.csv")
_14_data=pd.read_csv("NYCHVS 2014 Occupied File for ASA Challenge_CSV.csv")
_17_data=pd.read_csv("NYCHVS 2017 Occupied File for ASA Challenge_CSV.csv")

C:\Users\colum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\colum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\colum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\colum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,141,142,143,144,145,146,147,148,149,150,151,152) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\colum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\colum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\colum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\colum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
def clean(dataframe,link=False):
    dataframe["hhinc"]=np.where(dataframe["hhinc"].astype("str")=="999999",0,dataframe["hhinc"])
    dataframe["hhinc"]=np.where(dataframe["hhinc"].astype("str")=="999998",np.NaN,dataframe["hhinc"])
    dataframe["_30a"]=np.where(dataframe["_30a"].astype("str")=="99998",np.NaN,dataframe["_30a"])
    dataframe["_30a"]=np.where(dataframe["_30a"].astype("str")=="99999",np.NaN,dataframe["_30a"])
    if link==True:
        dataframe=dataframe[dataframe["linkage"].astype("str")=="1"]
    return dataframe

In [4]:
import numpy as np
_91_data=clean(_91_data)
_93_data=clean(_93_data)
_96_data=clean(_96_data)
_99_data=clean(_99_data)

In [5]:
_91={"linkage":"linkage","seqn":"seqn","year":"year","geo_id2":"geo_id2","sub-burough":"sba","sex_91":"_1b","income_91":"hhinc","age_91":"_1c","hispanic_91":"_1e","race_91":"_1f","year_move_91":"_4a","main_born_91":"_7a","mom_born_91":"_7b","dad_born_91":"_7c","lease_lenght_91":"_29","rent_91":"_30a","value_91":"_13","quality_91":"_39"}
     
_93={"linkage":"linkage","seqn":"seqn","year":"year","geo_id2":"geo_id2","sub-burough":"sba","sex_93":"_1b","income_93":"hhinc","age_93":"_1c","hispanic_93":"_1e","race_93":"_1f","year_move_93":"_4a","main_born_93":"_7a","mom_born_93":"_7b","dad_born_93":"_7c","lease_lenght_93":"_29","rent_93":"_30a","value_93":"_13","quality_93":"_39"}

_96={"linkage":"linkage","seqn":"seqn","year":"year","geo_id2":"geo_id2","sub-burough":"sba","sex_96":"_1b","income_96":"hhinc","age_96":"_1c","hispanic_96":"_1e","race_96":"_1f","year_move_96":"_4a","main_born_96":"_7a","mom_born_96":"_7b","dad_born_96":"_7c","lease_lenght_96":"_29","rent_96":"_30a","value_96":"_13","quality_96":"_39"}

_99={"linkage":"linkage","seqn":"seqn","year":"year","geo_id2":"geo_id2","sub-burough":"sba","sex_99":"_1b","income_99":"hhinc","age_99":"_1c","hispanic_99":"_1e","race_99":"_1f","year_move_99":"_4a","main_born_99":"_7a","mom_born_99":"_7b","dad_born_99":"_7c","lease_lenght_99":"_29","rent_99":"_30a","value_99":"_13","quality_99":"_39"}

_02={"seqn":"seqn","year":"year","geo_id2":"geo_id2","sub-burough":"sba","sex_02":"_1b","income_02":"hhinc","age_02":"_1c","hispanic_02":"_1e","race_02":"_1f","year_move_02":"_4a","main_born_02":"_7a","mom_born_02":"_7b","dad_born_02":"_7c","lease_lenght_02":"_29","rent_02":"_30a","value_02":"_13","quality_02":"_39"}

_05={"seqn":"seqn","year":"year","geo_id2":"geo_id2","sub-burough":"sba","sex_05":"_1b","income_05":"hhinc","age_05":"_1c","hispanic_05":"_1e","race_05":"_1f","year_move_05":"_4a","main_born_05":"_7a","mom_born_05":"_7b","dad_born_05":"_7c","lease_lenght_05":"_29","rent_05":"_30a","value_05":"_13","quality_05":"_39"}

_08={"seqn":"seqn","year":"year","geo_id2":"geo_id2","sub-burough":"sba","sex_08":"_1b","income_08":"hhinc","age_08":"_1c","hispanic_08":"_1e","race_08":"_1f","year_move_08":"_4a","main_born_08":"_7a","mom_born_08":"_7b","dad_born_08":"_7c","lease_lenght_08":"_29","rent_08":"_30a","value_08":"_13","quality_08":"_39"}

_11={"seqn":"seqn","year":"year","geo_id2":"geo_id2","sub-burough":"sba","sex_11":"_1b","income_11":"hhinc","age_11":"_1c","hispanic_11":"_1e","race_11":"_1f","year_move_11":"_4a","main_born_11":"_7a","mom_born_11":"_7b","dad_born_11":"_7c","lease_lenght_11":"_29","rent_11":"_30a","value_11":"_13","quality_11":"_39"}

_14={"seqn":"seqn","year":"year","geo_id2":"geo_id2","sub-burough":"sba","sex_14":"_1b","income_14":"hhinc","age_14":"_1c","hispanic_14":"_1e","race_14":"_1f","year_move_14":"_4a","main_born_14":"_7a","mom_born_14":"_7b","dad_born_14":"_7c","lease_lenght_14":"_29","rent_14":"_30a","value_14":"_13","quality_14":"_39"}
_17={"seqn":"seqn","year":"year","geo_id2":"geo_id2","sub-burough":"sba","sex_17":"_1b","income_17":"hhinc","age_17":"_1c","hispanic_17":"_1e","race_17":"_1f","year_move_17":"_4a","main_born_17":"_7a","mom_born_17":"_7b","dad_born_17":"_7c","lease_lenght_17":"_29","rent_17":"_30a","value_17":"_13","quality_17":"_39"}

In [6]:
clean_91=_91_data[list(_91.values())]
clean_91.columns=list(_91.keys())
clean_91=clean_91.loc[1:,:]
clean_93=_93_data[list(_93.values())]
clean_93.columns=list(_93.keys())
clean_93=clean_93.loc[1:,:]
clean_96=_96_data[list(_96.values())]
clean_96.columns=list(_96.keys())
clean_96=clean_96.loc[1:,:]
clean_99=_99_data[list(_99.values())]
clean_99.columns=list(_99.keys())
clean_99=clean_99.loc[1:,:]
clean_02=_02_data[list(_02.values())]
clean_02.columns=list(_02.keys())
clean_02=clean_02.loc[1:,:]
clean_05=_05_data[list(_05.values())]
clean_05.columns=list(_05.keys())
clean_05=clean_05.loc[1:,:]
clean_08=_08_data[list(_08.values())]
clean_08.columns=list(_08.keys())
clean_08=clean_08.loc[1:,:]
clean_11=_11_data[list(_11.values())]
clean_11.columns=list(_11.keys())
clean_11=clean_11.loc[1:,:]
clean_14=_14_data[list(_14.values())]
clean_14.columns=list(_14.keys())
clean_14=clean_14.loc[1:,:]
clean_17=_17_data[list(_17.values())]
clean_17.columns=list(_17.keys())
clean_17=clean_17.loc[1:,:]

In [7]:
def agg_rent_income(df,col1,col2):
    df[col1]=df[col1].astype("float")
    df[col2]=df[col2].astype("float")
    return df.groupby("sub-burough").aggregate({col1:"mean"}).reset_index().merge(df.groupby("sub-burough").aggregate({col2:"mean"}).reset_index(),on="sub-burough")

In [8]:
rent_income_average_91=agg_rent_income(clean_91,"rent_91","income_91")
rent_income_average_93=agg_rent_income(clean_93,"rent_93","income_93")
rent_income_average_96=agg_rent_income(clean_96,"rent_96","income_96")
rent_income_average_99=agg_rent_income(clean_99,"rent_99","income_99")

In [9]:
deltas_90s=rent_income_average_91.merge(rent_income_average_93,on="sub-burough",how='inner').merge(rent_income_average_96,on="sub-burough",how='inner').merge(rent_income_average_99,on="sub-burough",how='inner')

In [10]:
rent_income_average_02=agg_rent_income(clean_02,"rent_02","income_02")
rent_income_average_05=agg_rent_income(clean_05,"rent_05","income_05")
rent_income_average_08=agg_rent_income(clean_08,"rent_08","income_08")
delta_000s=rent_income_average_02.merge(rent_income_average_05,on="sub-burough",how='inner').merge(rent_income_average_08,on="sub-burough",how='inner')

In [11]:
rent_income_average_11=agg_rent_income(clean_11,"rent_11","income_11")
rent_income_average_14=agg_rent_income(clean_14,"rent_14","income_14")
rent_income_average_17=agg_rent_income(clean_17,"rent_17","income_17")
delta_10s=rent_income_average_11.merge(rent_income_average_14,on="sub-burough",how='inner').merge(rent_income_average_17,on="sub-burough",how='inner')

In [12]:
delta_1=clean_91.merge(clean_93,on=["linkage","seqn","geo_id2","sub-burough"],how="inner")
delta_1=delta_1.loc[1:,:]

In [13]:
delta_1["race_delta_93"]=(delta_1["race_91"]+delta_1["race_93"])
delta_1["hisp_delta_93"]=(delta_1["hispanic_91"]+delta_1["hispanic_93"])
delta_1["move_93"]=delta_1["year_move_91"]!=delta_1["year_move_93"]
delta_1["income_delta_93"]=(delta_1["income_93"].astype("float")-delta_1["income_91"].astype("float"))

In [14]:
delta_1["rent_delta_93"]=(delta_1["rent_93"].astype("float")-delta_1["rent_91"].astype("float"))

In [15]:
delta_2=clean_93.merge(clean_96,on=["linkage","seqn","geo_id2","sub-burough"],how="inner")
delta_2=delta_2.loc[1:,:]
delta_2["race_delta_96"]=(delta_2["race_93"]+delta_2["race_96"])
delta_2["hisp_delta_96"]=(delta_2["hispanic_93"]+delta_2["hispanic_96"])
delta_2["move_96"]=delta_2["year_move_93"]!=delta_2["year_move_96"]
delta_2["income_delta_96"]=(delta_2["income_96"].astype("float")-delta_2["income_93"].astype("float"))
delta_2["rent_delta_96"]=(delta_2["rent_96"].astype("float")-delta_2["rent_93"].astype("float"))

In [16]:
delta_3=clean_96.merge(clean_99,on=["linkage","seqn","geo_id2","sub-burough"],how="inner")
delta_3=delta_3.loc[1:,:]
delta_3["race_delta_99"]=(delta_3["race_96"]+delta_3["race_99"])
delta_3["hisp_delta_99"]=(delta_3["hispanic_96"]+delta_3["hispanic_99"])
delta_3["move_99"]=delta_3["year_move_96"]!=delta_3["year_move_99"]
delta_3["income_delta_99"]=(delta_3["income_99"].astype("int")-delta_3["income_96"].astype("int"))
delta_3["rent_delta_99"]=(delta_3["rent_99"].astype("float")-delta_3["rent_96"].astype("float"))

In [17]:
delta_1=delta_1.loc[:,["seqn","geo_id2","linkage","sub-burough","race_delta_93","hisp_delta_93","move_93","income_delta_93","rent_delta_93"]]

In [18]:
delta_2=delta_2.loc[:,["seqn","geo_id2","linkage","sub-burough","race_delta_96","hisp_delta_96","move_96","income_delta_96","rent_delta_96"]]

In [19]:
delta_3=delta_3.loc[:,["seqn","geo_id2","linkage","sub-burough","race_delta_99","hisp_delta_99","move_99","income_delta_99","rent_delta_99"]]

In [20]:
nineties_change=delta_1.merge(delta_3,on=["seqn","geo_id2","linkage","sub-burough"],how="inner").merge(delta_2,on=["seqn","geo_id2","linkage","sub-burough"],how="inner")

In [21]:
nineties_change["income_total"]=nineties_change["income_delta_93"]+nineties_change["income_delta_96"]+nineties_change["income_delta_99"]

In [22]:
nineties_change["rent_total"]=nineties_change["rent_delta_93"]+nineties_change["rent_delta_96"]+nineties_change["rent_delta_99"]

In [23]:
nineties_change

,seqn,geo_id2,linkage,sub-burough,race_delta_93,hisp_delta_93,move_93,income_delta_93,rent_delta_93,race_delta_99,...,move_99,income_delta_99,rent_delta_99,race_delta_96,hisp_delta_96,move_96,income_delta_96,rent_delta_96,income_total,rent_total
0,485,3603702,1,110,22,11,True,-8240.0,NaN,22,...,True,51272,NaN,22,11,True,5140.0,NaN,48172.0,NaN
1,487,3603702,1,110,11,11,False,5608.0,NaN,11,...,True,-1256,NaN,11,11,False,2456.0,NaN,6808.0,NaN
2,499,3603702,1,110,102,11,True,-26000.0,NaN,22,...,True,31184,83.0,22,11,True,-19384.0,NaN,-14200.0,NaN
3,504,3603702,1,110,22,11,True,21138.0,-100.0,22,...,True,4000,NaN,22,11,True,-9170.0,-320.0,15968.0,NaN
4,517,3603702,1,110,101,22,False,NaN,NaN,12,...,True,85088,NaN,11,22,False,-684.0,NaN,NaN,NaN
5,533,3603704,1,109,101,55,True,33000.0,20.0,11,...,True,-38,-10.0,11,52,False,-58300.0,-5.0,-25338.0,5.0
6,561,3603704,1,109,11,11,True,636.0,3.0,11,...,True,11524,3.0,11,11,True,720.0,0.0,12880.0,6.0
7,569,3603704,1,109,12,12,True,13000.0,NaN,12,...,True,9000,NaN,21,22,False,-13000.0,NaN,9000.0,NaN
8,608,3604006,1,208,22,11,True,-972.0,-67.0,22,...,True,-2784,0.0,22,11,False,-2128.0,17.0,-5884.0,-50.0
9,613,3603703,1,108,22,11,True,1260.0,NaN,22,...,True,25600,NaN,22,11,False,1200.0,NaN,28060.0,NaN
10,618,3604006,1,208,21,23,True,208.0,10.0,22,...,True,12440,20.0,12,33,True,552.0,0.0,13200.0,30.0
11,630,3603703,1,108,11,28,True,-23000.0,NaN,11,...,True,-10000,NaN,11,82,True,-7000.0,NaN,-40000.0,NaN
12,632,3604006,1,208,22,11,True,-20960.0,-25.0,22,...,True,48000,-25.0,22,11,True,1800.0,75.0,28840.0,25.0
13,636,3603703,1,108,12,18,True,-40000.0,NaN,12,...,True,-20750,NaN,21,81,True,4750.0,NaN,-56000.0,NaN
14,643,3603703,1,108,11,11,True,40500.0,NaN,11,...,True,5000,NaN,11,12,True,12500.0,NaN,58000.0,NaN
15,644,3604006,1,208,22,51,False,-4996.0,NaN,22,...,True,44400,NaN,22,11,True,5596.0,NaN,45000.0,NaN
16,662,3603703,1,108,11,11,False,1476.0,NaN,11,...,True,-2960,NaN,11,11,False,4800.0,NaN,3316.0,NaN
17,665,3604006,1,208,22,11,True,-1800.0,-259.0,22,...,True,-60000,NaN,22,11,True,107000.0,NaN,45200.0,NaN
18,668,3604012,1,207,11,11,True,1415.0,11.0,11,...,True,-14540,982.0,11,11,True,15260.0,14.0,2135.0,1007.0
19,673,3603709,1,107,11,22,False,1895.0,45.0,11,...,True,-10324,-16.0,11,21,False,4100.0,15.0,-4329.0,44.0
20,676,3603709,1,107,12,11,True,5400.0,21.0,12,...,True,-6730,66.0,21,13,True,-15270.0,137.0,-16600.0,224.0
21,678,3604012,1,207,81,11,True,9160.0,100.0,11,...,True,798,53.0,11,13,True,-20558.0,0.0,-10600.0,153.0
22,683,3603709,1,107,21,22,True,4000.0,2.0,11,...,True,1000,0.0,11,22,True,-7800.0,-185.0,-2800.0,-183.0
23,684,3604012,1,207,11,11,False,824.0,38.0,11,...,True,7680,-29.0,11,11,True,-8804.0,-22.0,-300.0,-13.0
24,689,3604012,1,207,101,66,True,23920.0,150.0,11,...,True,-21500,270.0,11,66,True,-7420.0,-220.0,-5000.0,200.0
25,707,3603709,1,107,82,11,True,NaN,NaN,88,...,True,22000,NaN,28,11,False,8000.0,NaN,NaN,NaN
26,724,3604005,1,206,11,11,True,NaN,NaN,11,...,True,16548,NaN,11,11,False,-15500.0,NaN,NaN,NaN
27,731,3603709,1,107,22,11,False,9200.0,NaN,22,...,True,10936,NaN,22,11,False,3864.0,NaN,24000.0,NaN
28,734,3604005,1,206,11,11,False,-16000.0,21.0,11,...,True,17000,50.0,11,11,True,-7000.0,55.0,-6000.0,126.0
29,740,3603701,1,106,22,81,True,NaN,NaN,22,...,True,11760,-64.0,22,11,True,0.0,64.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6236,45067,3603903,1,501,3,3,False,NaN,5.0,2,...,True,56600,21.0,2,3,True,18000.0,19.0,NaN,45.0
6237,45073,3603810,1,301,2,2,True,NaN,430.0,2,...,True,-6000,25.0,2,2,True,75400.0,50.0,NaN,505.0
6238,45080,3604101,1,401,2,2,True,5500.0,-40.0,2,...,True,-6000,200.0,2,2,True,4500.0,-100.0,4000.0,60.0
6239,45089,3603810,1,301,2,2,False,NaN,NaN,2,...,True,-264107,NaN,2,2,False,81366.0,NaN,NaN,NaN
6240,45092,3604101,1,401,2,2,True,-4904.0,NaN,2,...,True,22600,NaN,2,2,False,-9566.0,NaN,8130.0,NaN
6241,45093,3603903,1,501,11,4,True,-21000.0,NaN,2,...,True,-30000,NaN,2,4,True,22000.0,NaN,-29000.0,NaN
6242,45106,3603810,1,301,99,2,False,NaN,NaN,2,...,True,-64000,NaN,2,2,True,35000.0,NaN,NaN,NaN
6243,45109,3604101,1,401,2,2,False,NaN,NaN,2,...,True,-200,NaN,2,2,False,-6065.0,NaN,NaN,NaN
6244,45110,3603903,1,501,2,2,True,NaN,NaN,2,...,True,30352,NaN,2,2,False,11600.0,NaN,NaN,NaN
6245,45125,3603810,1,301,2,2,False,-23000.0,NaN,2,...,True,-58800,NaN,2,2,True,29000.0,NaN,-52800.0,NaN
6246,45128,3604101,1,401,2,2,True,NaN,NaN,2,...,True,-4000,NaN,2,2,True,17800.0,NaN,NaN,NaN
6247,45130,3603903,1,501,2,2,False,-39100.0,NaN,2,...,True,48120,NaN,2,2,True,20800.0,NaN,29820.0,NaN
6248,45132,3604009,1,218,2,2,True,NaN,150.0,3,...,True,2000,100.0,3,2,True,-27000.0,50.0,NaN,300.0
6249,45164,3604106,1,408,2,2,False,34000.0,NaN,2,...,True,-38200,NaN,2,2,True,-53800.0,NaN,-58000.0,NaN
6250,45181,3604101,1,401,2,2,True,NaN,NaN,2,...,True,-43690,NaN,2,2,True,-6310.0,NaN,NaN,NaN
6251,45187,3604015,1,214,2,4,True,11400.0,25.0,2,...,True,-13000,0.0,2,4,True,46600.0,50.0,45000.0,75.0
6252,45192,3604103,1,407,2,2,False,NaN,NaN,2,...,True,7200,NaN,2,2,False,11700.0,NaN,NaN,NaN
6253,45194,3604007,1,216,4,2,False,3956.0,NaN,4,...,True,12800,NaN,4,2,True,13044.0,NaN,29800.0,NaN
6254,45196,3604113,1,410,12,6,False,3000.0,0.0,4,...,True,-25000,-150.0,3,2,True,12000.0,50.0,-10000.0,-100.0
6255,45198,3604107,1,404,2,10,False,-11400.0,0.0,2,...,True,30000,0.0,2,11,True,900.0,50.0,19500.0,50.0
6256,45203,3604009,1,218,2,2,False,NaN,15.0,4,...,True,22709,50.0,3,2,True,2324.0,185.0,NaN,250.0
6257,45206,3604105,1,413,4,2,True,-7920.0,NaN,4,...,True,-88000,NaN,4,2,True,99000.0,NaN,3080.0,NaN
6258,45208,3604106,1,408,2,2,True,NaN,NaN,2,...,True,-2700,NaN,2,2,True,-21638.0,NaN,NaN,NaN
6259,45209,3604010,1,217,4,2,True,-28728.0,-250.0,4,...,True,-76724,-70.0,4,2,True,80228.0,170.0,-25224.0,-150.0
6260,45214,3604015,1,214,2,2,True,NaN,0.0,2,...,True,-100000,25.0,2,2,True,95000.0,110.0,NaN,135.0
6261,45227,3604103,1,407,2,2,False,NaN,NaN,2,...,True,-34500,NaN,2,2,False,28500.0,NaN,NaN,NaN
6262,45228,3604113,1,410,12,6,True,2000.0,0.0,16,...,True,60000,0.0,10,2,True,6000.0,0.0,68000.0,0.0
6263,45230,3604105,1,413,18,3,True,NaN,-50.0,10,...,True,-35000,-100.0,10,2,True,24000.0,350.0,NaN,200.0
6264,45231,3604101,1,401,2,2,True,NaN,NaN,2,...,True,-98850,NaN,2,2,False,61890.0,NaN,NaN,NaN
6265,45233,3604105,1,413,4,2,False,NaN,0.0,9,...,True,28000,100.0,3,3,True,9000.0,0.0,NaN,100.0

In [24]:
nineties_change.groupby("sub-burough").aggregate({"income_total":"mean"}).reset_index().merge(nineties_change.groupby("sub-burough").aggregate({"rent_total":"mean"}).reset_index(),on="sub-burough")

   sub-burough  income_total  rent_total
0          202  -4404.000000    0.000000
1          203  -1656.000000    0.000000
2          204   8840.000000    0.000000
3          205  16816.000000  125.000000
4          208   9674.666667  115.222222
5          209   8478.849462  121.253165
6          210  23702.752294  124.300000
7          211   7567.148148  176.636364
8          212   9237.290698  187.431373
9          213  10780.971429  179.040000
10         214  11948.356436  179.306818
11         215  16439.941176  126.107143
12         216   8292.446154  108.345455
13         217   8413.814815  131.770270
14         218  11461.888889  127.637931
15         301  24661.971698  337.806452
16         302  14113.087302  155.728682
17         303  21413.415254  342.666667
18         304  36784.668712  352.208333
19         305  30279.156757  347.585799
20         306  25104.093137  422.231156
21         307  12940.250000  104.552632
22         308   5136.632353  105.875000
23         309   2667.872093  150.827160
24         310   7371.867647  133.094241
25         401   8629.036145  122.856209
26         402  13833.678571  134.491525
27         403   6533.365591  114.918033
28         404   6844.438776  117.051282
29         405   6715.892086  144.666667
30         406   3352.809524  222.833333
31         407  12930.475610  132.194805
32         408   7678.495798  113.514706
33         409  10166.318182  155.162791
34         410   6941.186667  125.000000
35         411   8936.942308  170.600000
36         412  13546.511278  134.883721
37         413  15811.346154  111.050000
38         414   4079.974026  146.175439
39         501  15389.442748  131.500000
40         502  11619.166667   90.727273
41         503   8317.842105   21.800000
42         101   4864.692308   82.733333
43         102  -1873.533333   82.314286
44         103  -2219.400000  178.354839
45         104  -7172.750000  116.580645
46         105   2389.125000   93.828571
47         106   6463.437500  187.171429
48         107  -2162.527778   96.058824
49         108  12592.162162  107.250000
50         109  13215.968750  128.407407
51         110  11817.593750  100.250000
52         201   6593.235294  137.080000
53         202   2653.772727  157.590909
54         203   -846.826087  147.000000
55         204  11537.571429  119.045455
56         205  17927.208333  159.421053
57         206  17630.923077  131.954545
58         207    919.911765  206.809524
59         208  -4862.968750  118.863636

In [25]:
pd.read_csv("NYCHVS 2008 Occupied File for ASA Challenge_CSV.csv")

C:\Users\colum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,recordtype,borough,_d1,_d2,_d3,_d4,_d5,_d6,_e1,_e2,...,hhincva,sub,under6,under18,hhweight,seqn,year,linkage,sba,geo_id2
0,Record Type,Borough,"Condition of Exterior Walls: Missing brick, si...",Condition of Exterior Walls: Sloping or bulgin...,Condition of Exterior Walls: Major cracks in o...,Condition of Exterior Walls: Loose or hanging ...,Condition of Exterior Walls: None of these pro...,Condition of Exterior Walls: Unable to observe...,Condition of Windows: Broken or missing windows,Condition of Windows: Rotten/loose windows,...,"Household Income from VA Payments, Unemploymen...",Sub-Borough Area,Household Member under age 6,Household Member under age 18,Household Sampling Weight (5 implied decimal p...,Sequence Number,Year Identifier,Linkage Indicator,Borough and Sub-Borough Area,GEO.id2
1,1,1,9,9,9,9,1,9,9,9,...,9999999,1,2,2,22887360,82136,2008,1,101,3603710
2,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,16922738,75808,2008,1,101,3603710
3,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,19547348,63903,2008,1,101,3603710
4,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,2,23560516,49174,2008,1,101,3603710
5,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,2,20832820,4104,2008,1,101,3603710
6,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,17150896,10188,2008,4,101,3603710
7,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,18748376,32783,2008,1,101,3603710
8,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,18736916,17086,2008,4,101,3603710
9,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,18697464,94878,2008,1,101,3603710
10,1,1,9,9,9,9,1,9,9,1,...,9999999,1,1,3,18907198,80772,2008,1,101,3603710
11,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,23560516,95954,2008,1,101,3603710
12,1,1,9,9,9,9,1,9,9,9,...,9999999,1,2,3,18736916,48867,2008,1,101,3603710
13,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,21240488,29763,2008,1,101,3603710
14,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,2,18736916,19604,2008,1,101,3603710
15,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,20832820,51111,2008,4,101,3603710
16,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,18736916,76237,2008,1,101,3603710
17,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,16922738,30696,2008,1,101,3603710
18,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,18907198,43209,2008,1,101,3603710
19,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,22870528,84033,2008,1,101,3603710
20,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,4,19082348,83712,2008,1,101,3603710
21,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,19173280,40516,2008,1,101,3603710
22,1,1,9,9,9,9,1,9,9,9,...,9999999,1,2,2,19006028,23572,2008,1,101,3603710
23,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,21183022,11264,2008,1,101,3603710
24,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,4,18333116,64804,2008,1,101,3603710
25,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,16922738,19453,2008,1,101,3603710
26,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,25346168,62786,2008,1,101,3603710
27,1,1,9,9,9,9,1,9,9,9,...,9999999,1,2,2,18748376,81469,2008,1,101,3603710
28,1,1,9,9,9,9,1,9,9,9,...,9999999,1,1,1,19006028,55384,2008,1,101,3603710
29,1,1,9,9,9,9,1,9,9,9,...,4200,1,1,1,22870528,86626,2008,1,101,3603710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17926,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,1,3524859,56901,2008,4,503,3603901
17927,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,1,3524859,75810,2008,4,503,3603901
17928,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,1,3524859,2375,2008,4,503,3603901
17929,1,5,9,9,9,9,1,9,9,9,...,9999999,1,3,6,3524859,12331,2008,4,501,3603903
17930,1,5,9,9,9,9,1,9,9,9,...,9999999,1,1,1,3524859,86316,2008,4,501,3603903
17931,1,5,9,9,9,9,1,9,9,9,...,9999999,1,3,4,3524859,20442,2008,4,501,3603903
17932,1,5,9,9,9,9,1,9,9,9,...,9999999,2,1,1,3524859,9065,2008,4,502,3603902
17933,1,5,9,9,9,9,1,9,9,9,...,9999999,1,1,1,3524859,38193,2008,4,501,3603903
17934,1,5,9,9,9,9,1,9,9,9,...,9999999,1,1,1,3524859,26579,2008,4,501,3603903
17935,1,5,9,9,9,9,1,9,9,9,...,9999999,1,1,1,3524859,66730,2008,4,501,3603903
17936,1,5,9,9,9,9,1,9,9,9,...,9999999,2,1,1,3524859,170,2008,4,502,3603902
17937,1,5,9,9,9,9,1,9,9,9,...,9999999,2,1,1,3524859,8859,2008,4,502,3603902
17938,1,5,9,9,9,9,1,9,9,9,...,9999999,2,3,3,3524859,50937,2008,4,502,3603902
17939,1,5,9,9,9,9,1,9,9,9,...,9999999,3,3,4,3524859,17968,2008,4,503,3603901
17940,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,2,3524859,24300,2008,4,503,3603901
17941,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,1,3524859,66084,2008,4,503,3603901
17942,1,5,9,9,9,9,1,9,9,9,...,9999999,3,2,2,3524859,76365,2008,4,503,3603901
17943,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,1,3524859,46631,2008,4,503,3603901
17944,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,1,3524859,46397,2008,4,503,3603901
17945,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,3,3524859,14656,2008,4,503,3603901
17946,1,5,9,9,9,9,1,9,9,9,...,9999999,1,1,1,796331,84878,2008,1,501,3603903
17947,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,1,502955,17634,2008,1,503,3603901
17948,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,1,796331,2592,2008,1,503,3603901
17949,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,4,502955,46673,2008,1,503,3603901
17950,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,1,408074,26466,2008,2,503,3603901
17951,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,1,646105,83780,2008,2,503,3603901
17952,1,5,9,9,9,9,1,9,9,9,...,9999999,2,1,3,426579,62950,2008,4,502,3603902
17953,1,5,9,9,9,9,1,9,9,9,...,9999999,2,1,1,426579,42929,2008,4,502,3603902
17954,1,5,9,9,9,9,1,9,9,9,...,9999999,3,1,1,426579,87395,2008,4,503,3603901
17955,1,5,9,9,9,9,1,9,9,9,...,9999999,1,1,1,433138,26391,2008,4,501,3603903

1) Use the data from 2002-2017 and track "gentrification"

2) Use 2002,2005,2008 data and compare 2000 and 2010 response rates (fit model)
-Maybe also do this in the 90s

3) Apply this model to 2011,2014,2017

In [26]:
pd.read_csv("participationrates2010.txt",sep="||")

C:\Users\colum\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

FileNotFoundError: [Errno 2] No such file or directory: 'participationrates2010.txt'

In [ ]:
census=pd.read_csv("planning_database_NYC_tracts.csv",encoding="latin")